/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\VULCAN\\source\\repos\\limshung-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-cfebf258",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cfebf258").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-308b2ad4",
    path: "/docs/iview-comment-tree/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-308b2ad4").then(next)
    },
  },
  {
    path: "/docs/iview-comment-tree/index.html",
    redirect: "/docs/iview-comment-tree/"
  },
  {
    name: "v-fcfa9c8a",
    path: "/blogs/blog/blog-init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcfa9c8a").then(next)
    },
  },
  {
    name: "v-1f69be38",
    path: "/blogs/leetcook/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f69be38").then(next)
    },
  },
  {
    path: "/blogs/leetcook/index.html",
    redirect: "/blogs/leetcook/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-49a56e2a",
    path: "/tag/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-49a56e2a").then(next)
    },
    meta: {"pid":"tags","id":"前端"}
  },
  {
    path: "/tag/前端/index.html",
    redirect: "/tag/前端/"
  },
  {
    name: "v-18535602",
    path: "/tag/front-end/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-18535602").then(next)
    },
    meta: {"pid":"tags","id":"front-end"}
  },
  {
    path: "/tag/front-end/index.html",
    redirect: "/tag/front-end/"
  },
  {
    name: "v-42aee080",
    path: "/categories/博客/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-42aee080").then(next)
    },
    meta: {"pid":"categories","id":"博客"}
  },
  {
    path: "/categories/博客/index.html",
    redirect: "/categories/博客/"
  },
  {
    name: "v-39ba213e",
    path: "/categories/LeetCook/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-39ba213e").then(next)
    },
    meta: {"pid":"categories","id":"LeetCook"}
  },
  {
    path: "/categories/LeetCook/index.html",
    redirect: "/categories/LeetCook/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]