/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\Users\\VULCAN\\source\\repos\\limshung-blog\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-cfebf258",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cfebf258").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-6983bd22",
    path: "/blogs/algorithm/union-find.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6983bd22").then(next)
    },
  },
  {
    name: "v-8bfd3d66",
    path: "/blogs/algorithm/priority-queue-heap.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8bfd3d66").then(next)
    },
  },
  {
    name: "v-fcfa9c8a",
    path: "/blogs/blog/blog-init.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-fcfa9c8a").then(next)
    },
  },
  {
    name: "v-1f69be38",
    path: "/blogs/leetcook/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f69be38").then(next)
    },
  },
  {
    path: "/blogs/leetcook/index.html",
    redirect: "/blogs/leetcook/"
  },
  {
    name: "v-4bc0f832",
    path: "/blogs/node/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4bc0f832").then(next)
    },
  },
  {
    name: "v-308b2ad4",
    path: "/docs/iview-comment-tree/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-308b2ad4").then(next)
    },
  },
  {
    path: "/docs/iview-comment-tree/index.html",
    redirect: "/docs/iview-comment-tree/"
  },
  {
    name: "v-b1564aac",
    path: "/tag/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tags", "v-b1564aac").then(next)
    },
    meta: {"pid":"tags","id":"tags"}
  },
  {
    path: "/tag/index.html",
    redirect: "/tag/"
  },
  {
    name: "v-ef9325c4",
    path: "/categories/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("FrontmatterKey", "v-ef9325c4").then(next)
    },
    meta: {"pid":"categories","id":"categories"}
  },
  {
    path: "/categories/index.html",
    redirect: "/categories/"
  },
  {
    name: "v-6319eb4e",
    path: "/timeline/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("TimeLines", "v-6319eb4e").then(next)
    },
    meta: {"pid":"timeline","id":"timeline"}
  },
  {
    path: "/timeline/index.html",
    redirect: "/timeline/"
  },
  {
    name: "v-01516bac",
    path: "/tag/图/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-01516bac").then(next)
    },
    meta: {"pid":"tags","id":"图"}
  },
  {
    path: "/tag/图/index.html",
    redirect: "/tag/图/"
  },
  {
    name: "v-29896eb6",
    path: "/tag/并查集/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-29896eb6").then(next)
    },
    meta: {"pid":"tags","id":"并查集"}
  },
  {
    path: "/tag/并查集/index.html",
    redirect: "/tag/并查集/"
  },
  {
    name: "v-0c0040b5",
    path: "/tag/堆/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-0c0040b5").then(next)
    },
    meta: {"pid":"tags","id":"堆"}
  },
  {
    path: "/tag/堆/index.html",
    redirect: "/tag/堆/"
  },
  {
    name: "v-743eddda",
    path: "/tag/优先队列/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-743eddda").then(next)
    },
    meta: {"pid":"tags","id":"优先队列"}
  },
  {
    path: "/tag/优先队列/index.html",
    redirect: "/tag/优先队列/"
  },
  {
    name: "v-49a56e2a",
    path: "/tag/前端/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-49a56e2a").then(next)
    },
    meta: {"pid":"tags","id":"前端"}
  },
  {
    path: "/tag/前端/index.html",
    redirect: "/tag/前端/"
  },
  {
    name: "v-131e7410",
    path: "/tag/vue3/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Tag", "v-131e7410").then(next)
    },
    meta: {"pid":"tags","id":"vue3"}
  },
  {
    path: "/tag/vue3/index.html",
    redirect: "/tag/vue3/"
  },
  {
    name: "v-f37f30be",
    path: "/categories/算法/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-f37f30be").then(next)
    },
    meta: {"pid":"categories","id":"算法"}
  },
  {
    path: "/categories/算法/index.html",
    redirect: "/categories/算法/"
  },
  {
    name: "v-42aee080",
    path: "/categories/博客/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-42aee080").then(next)
    },
    meta: {"pid":"categories","id":"博客"}
  },
  {
    path: "/categories/博客/index.html",
    redirect: "/categories/博客/"
  },
  {
    name: "v-39ba213e",
    path: "/categories/LeetCook/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-39ba213e").then(next)
    },
    meta: {"pid":"categories","id":"LeetCook"}
  },
  {
    path: "/categories/LeetCook/index.html",
    redirect: "/categories/LeetCook/"
  },
  {
    name: "v-65506e4c",
    path: "/categories/学习笔记/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Category", "v-65506e4c").then(next)
    },
    meta: {"pid":"categories","id":"学习笔记"}
  },
  {
    path: "/categories/学习笔记/index.html",
    redirect: "/categories/学习笔记/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]