/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "limshung's blog",
  "description": "一个普普通通的博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "limshung's blog",
        "tagline": "一个普普通通的博客",
        "bgImage": "/banner.jpg",
        "bgImageStyle": {
          "height": "350px",
          "color": "white",
          "text-shadow": "black 0.1em 0.1em 0.2em"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2f6ab9b0",
      "path": "/"
    },
    {
      "title": "博客初始化",
      "frontmatter": {
        "date": "2021/2/9",
        "title": "博客初始化",
        "categories": [
          "博客"
        ],
        "tags": [
          "前端"
        ]
      },
      "regularPath": "/blogs/blog/%E5%8D%9A%E5%AE%A2%E5%88%9D%E5%A7%8B%E5%8C%96.html",
      "relativePath": "blogs/blog/博客初始化.md",
      "key": "v-26f10b30",
      "path": "/blogs/blog/%E5%8D%9A%E5%AE%A2%E5%88%9D%E5%A7%8B%E5%8C%96.html",
      "headers": [
        {
          "level": 2,
          "title": "博客转移",
          "slug": "博客转移"
        },
        {
          "level": 2,
          "title": "将来目标",
          "slug": "将来目标"
        }
      ]
    },
    {
      "title": "iview-comment-tree文档",
      "frontmatter": {
        "title": "iview-comment-tree文档",
        "date": "2021/2/9"
      },
      "regularPath": "/docs/iview-comment-tree/",
      "relativePath": "docs/iview-comment-tree/README.md",
      "key": "v-986b61b0",
      "path": "/docs/iview-comment-tree/"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端 Tags"
      },
      "regularPath": "/tag/%E5%89%8D%E7%AB%AF/",
      "key": "v-49a56e2a",
      "path": "/tag/前端/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "博客 Categories"
      },
      "regularPath": "/categories/%E5%8D%9A%E5%AE%A2/",
      "key": "v-42aee080",
      "path": "/categories/博客/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "文档",
        "icon": "reco-message",
        "items": [
          {
            "text": "iview-comment-tree",
            "link": "/docs/iview-comment-tree/"
          }
        ]
      },
      {
        "text": "联系我",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/Unnatural16",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {},
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "博客"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "此博客使用的vuepress主题",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "author": "limshung",
    "authorAvatar": "/avatar.png",
    "record": "粤ICP备2020102443号-1",
    "startYear": "2020",
    "subSidebar": "auto",
    "valineConfig": {
      "appId": "TT6vCSJpbBP8EawVGAJ4KnEV-gzGzoHsz",
      "appKey": "yEVYreP5AO2XVyc9oUY4hycE"
    }
  },
  "locales": {
    "/": {
      "lang": "zh-CN",
      "path": "/"
    }
  }
}