/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "limshung's blog",
  "description": "一个普普通通的博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/favicon.ico"
      }
    ],
    [
      "meta",
      {
        "name": "viewport",
        "content": "width=device-width,initial-scale=1,user-scalable=no"
      }
    ]
  ],
  "pages": [
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroText": "limshung's blog",
        "tagline": "一个普普通通的博客",
        "bgImage": "/banner.jpg",
        "bgImageStyle": {
          "height": "350px",
          "color": "white",
          "text-shadow": "black 0.1em 0.1em 0.2em"
        },
        "isShowTitleInHome": false
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-cfebf258",
      "path": "/",
      "lastUpdated": "2/9/2021, 6:24:32 PM"
    },
    {
      "title": "并查集",
      "frontmatter": {
        "title": "并查集",
        "date": "2021/2/12",
        "categories": [
          "算法"
        ],
        "tags": [
          "图",
          "并查集"
        ]
      },
      "regularPath": "/blogs/algorithm/union-find.html",
      "relativePath": "blogs/algorithm/union-find.md",
      "key": "v-6983bd22",
      "path": "/blogs/algorithm/union-find.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "代码模板",
          "slug": "代码模板"
        }
      ],
      "lastUpdated": "2/15/2021, 6:35:54 PM"
    },
    {
      "title": "优先队列-堆",
      "frontmatter": {
        "title": "优先队列-堆",
        "date": "2021/2/12",
        "categories": [
          "算法"
        ],
        "tags": [
          "堆",
          "优先队列"
        ]
      },
      "regularPath": "/blogs/algorithm/priority-queue-heap.html",
      "relativePath": "blogs/algorithm/priority-queue-heap.md",
      "key": "v-8bfd3d66",
      "path": "/blogs/algorithm/priority-queue-heap.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 3,
          "title": "数组",
          "slug": "数组"
        },
        {
          "level": 3,
          "title": "树",
          "slug": "树"
        },
        {
          "level": 3,
          "title": "堆",
          "slug": "堆"
        },
        {
          "level": 2,
          "title": "实现",
          "slug": "实现"
        }
      ],
      "lastUpdated": "2/15/2021, 6:35:54 PM"
    },
    {
      "title": "博客初始化",
      "frontmatter": {
        "date": "2021/2/9",
        "title": "博客初始化",
        "categories": [
          "博客"
        ],
        "tags": [
          "前端"
        ]
      },
      "regularPath": "/blogs/blog/blog-init.html",
      "relativePath": "blogs/blog/blog-init.md",
      "key": "v-fcfa9c8a",
      "path": "/blogs/blog/blog-init.html",
      "headers": [
        {
          "level": 2,
          "title": "博客转移",
          "slug": "博客转移"
        },
        {
          "level": 2,
          "title": "将来目标",
          "slug": "将来目标"
        },
        {
          "level": 2,
          "title": "博客注意点",
          "slug": "博客注意点"
        },
        {
          "level": 3,
          "title": "最后更新时间",
          "slug": "最后更新时间"
        },
        {
          "level": 3,
          "title": "中文路径",
          "slug": "中文路径"
        },
        {
          "level": 3,
          "title": "显示时间",
          "slug": "显示时间"
        }
      ],
      "lastUpdated": "2/15/2021, 6:35:54 PM"
    },
    {
      "title": "LeetCook项目",
      "frontmatter": {
        "date": "2021/2/10",
        "title": "LeetCook项目",
        "categories": [
          "LeetCook"
        ],
        "tags": [
          "前端"
        ]
      },
      "regularPath": "/blogs/leetcook/",
      "relativePath": "blogs/leetcook/README.md",
      "key": "v-1f69be38",
      "path": "/blogs/leetcook/",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 2,
          "title": "技术栈",
          "slug": "技术栈"
        },
        {
          "level": 2,
          "title": "项目运行",
          "slug": "项目运行"
        },
        {
          "level": 2,
          "title": "功能",
          "slug": "功能"
        },
        {
          "level": 3,
          "title": "已完成",
          "slug": "已完成"
        },
        {
          "level": 3,
          "title": "待完成",
          "slug": "待完成"
        },
        {
          "level": 2,
          "title": "后端交互",
          "slug": "后端交互"
        },
        {
          "level": 2,
          "title": "部分截图",
          "slug": "部分截图"
        }
      ],
      "lastUpdated": "2/15/2021, 6:35:54 PM"
    },
    {
      "title": "Vue3笔记",
      "frontmatter": {
        "date": "2021/2/21",
        "title": "Vue3笔记",
        "categories": [
          "学习笔记"
        ],
        "tags": [
          "前端",
          "vue3"
        ]
      },
      "regularPath": "/blogs/node/vue3.html",
      "relativePath": "blogs/node/vue3.md",
      "key": "v-4bc0f832",
      "path": "/blogs/node/vue3.html",
      "headers": [
        {
          "level": 2,
          "title": "介绍",
          "slug": "介绍"
        },
        {
          "level": 3,
          "title": "定义组件",
          "slug": "定义组件"
        },
        {
          "level": 3,
          "title": "定义响应式",
          "slug": "定义响应式"
        }
      ]
    },
    {
      "title": "iview-comment-tree文档",
      "frontmatter": {
        "title": "iview-comment-tree文档",
        "date": "2021/2/9"
      },
      "regularPath": "/docs/iview-comment-tree/",
      "relativePath": "docs/iview-comment-tree/README.md",
      "key": "v-308b2ad4",
      "path": "/docs/iview-comment-tree/",
      "lastUpdated": "2/12/2021, 11:21:48 AM"
    },
    {
      "frontmatter": {
        "layout": "Tags",
        "title": "Tags"
      },
      "regularPath": "/tag/",
      "key": "v-b1564aac",
      "path": "/tag/"
    },
    {
      "frontmatter": {
        "layout": "FrontmatterKey",
        "title": "Categories"
      },
      "regularPath": "/categories/",
      "key": "v-ef9325c4",
      "path": "/categories/"
    },
    {
      "frontmatter": {
        "layout": "TimeLines",
        "title": "Timeline"
      },
      "regularPath": "/timeline/",
      "key": "v-6319eb4e",
      "path": "/timeline/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "图 Tags"
      },
      "regularPath": "/tag/%E5%9B%BE/",
      "key": "v-01516bac",
      "path": "/tag/图/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "并查集 Tags"
      },
      "regularPath": "/tag/%E5%B9%B6%E6%9F%A5%E9%9B%86/",
      "key": "v-29896eb6",
      "path": "/tag/并查集/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "堆 Tags"
      },
      "regularPath": "/tag/%E5%A0%86/",
      "key": "v-0c0040b5",
      "path": "/tag/堆/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "优先队列 Tags"
      },
      "regularPath": "/tag/%E4%BC%98%E5%85%88%E9%98%9F%E5%88%97/",
      "key": "v-743eddda",
      "path": "/tag/优先队列/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "前端 Tags"
      },
      "regularPath": "/tag/%E5%89%8D%E7%AB%AF/",
      "key": "v-49a56e2a",
      "path": "/tag/前端/"
    },
    {
      "frontmatter": {
        "layout": "Tag",
        "title": "vue3 Tags"
      },
      "regularPath": "/tag/vue3/",
      "key": "v-131e7410",
      "path": "/tag/vue3/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "算法 Categories"
      },
      "regularPath": "/categories/%E7%AE%97%E6%B3%95/",
      "key": "v-f37f30be",
      "path": "/categories/算法/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "博客 Categories"
      },
      "regularPath": "/categories/%E5%8D%9A%E5%AE%A2/",
      "key": "v-42aee080",
      "path": "/categories/博客/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "LeetCook Categories"
      },
      "regularPath": "/categories/LeetCook/",
      "key": "v-39ba213e",
      "path": "/categories/LeetCook/"
    },
    {
      "frontmatter": {
        "layout": "Category",
        "title": "学习笔记 Categories"
      },
      "regularPath": "/categories/%E5%AD%A6%E4%B9%A0%E7%AC%94%E8%AE%B0/",
      "key": "v-65506e4c",
      "path": "/categories/学习笔记/"
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "主页",
        "link": "/",
        "icon": "reco-home"
      },
      {
        "text": "时间线",
        "link": "/timeline/",
        "icon": "reco-date"
      },
      {
        "text": "文档",
        "icon": "reco-message",
        "items": [
          {
            "text": "iview-comment-tree",
            "link": "/docs/iview-comment-tree/"
          }
        ]
      },
      {
        "text": "联系我",
        "icon": "reco-message",
        "items": [
          {
            "text": "GitHub",
            "link": "https://github.com/Unnatural16",
            "icon": "reco-github"
          }
        ]
      }
    ],
    "sidebar": {},
    "type": "blog",
    "blogConfig": {
      "category": {
        "location": 2,
        "text": "分类"
      },
      "tag": {
        "location": 3,
        "text": "标签"
      }
    },
    "friendLink": [
      {
        "title": "vuepress-theme-reco",
        "desc": "此博客使用的vuepress主题",
        "avatar": "https://vuepress-theme-reco.recoluan.com/icon_vuepress_reco.png",
        "link": "https://vuepress-theme-reco.recoluan.com"
      }
    ],
    "search": true,
    "searchMaxSuggestions": 10,
    "lastUpdated": "最后更新时间",
    "author": "limshung",
    "authorAvatar": "/avatar.png",
    "record": "粤ICP备2020102443号-1",
    "startYear": "2020",
    "subSidebar": "auto",
    "valineConfig": {
      "appId": "TT6vCSJpbBP8EawVGAJ4KnEV-gzGzoHsz",
      "appKey": "yEVYreP5AO2XVyc9oUY4hycE"
    }
  }
}