/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "前端": {
      "key": "前端",
      "scope": "tags",
      "path": "/tag/前端/",
      "pageKeys": [
        "v-26f10b30"
      ]
    }
  },
  "categories": {
    "博客": {
      "key": "博客",
      "scope": "categories",
      "path": "/categories/博客/",
      "pageKeys": [
        "v-26f10b30"
      ]
    }
  },
  "timeline": {}
}