/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "前端": {
      "key": "前端",
      "scope": "tags",
      "path": "/tag/前端/",
      "pageKeys": [
        "v-fcfa9c8a"
      ]
    },
    "front-end": {
      "key": "front-end",
      "scope": "tags",
      "path": "/tag/front-end/",
      "pageKeys": [
        "v-1f69be38"
      ]
    }
  },
  "categories": {
    "博客": {
      "key": "博客",
      "scope": "categories",
      "path": "/categories/博客/",
      "pageKeys": [
        "v-fcfa9c8a"
      ]
    },
    "LeetCook": {
      "key": "LeetCook",
      "scope": "categories",
      "path": "/categories/LeetCook/",
      "pageKeys": [
        "v-1f69be38"
      ]
    }
  },
  "timeline": {}
}