/**
 * Generated by "@vuepress/plugin-blog"
 */
export default {
  "tags": {
    "heap": {
      "key": "heap",
      "scope": "tags",
      "path": "/tag/heap/",
      "pageKeys": [
        "v-8bfd3d66"
      ]
    },
    "priority-queue": {
      "key": "priority-queue",
      "scope": "tags",
      "path": "/tag/priority-queue/",
      "pageKeys": [
        "v-8bfd3d66"
      ]
    },
    "array": {
      "key": "array",
      "scope": "tags",
      "path": "/tag/array/",
      "pageKeys": [
        "v-8bfd3d66"
      ]
    },
    "front-end": {
      "key": "front-end",
      "scope": "tags",
      "path": "/tag/front-end/",
      "pageKeys": [
        "v-1f69be38",
        "v-fcfa9c8a"
      ]
    },
    "union-find": {
      "key": "union-find",
      "scope": "tags",
      "path": "/tag/union-find/",
      "pageKeys": [
        "v-6983bd22"
      ]
    },
    "graph": {
      "key": "graph",
      "scope": "tags",
      "path": "/tag/graph/",
      "pageKeys": [
        "v-6983bd22"
      ]
    }
  },
  "categories": {
    "algorithm": {
      "key": "algorithm",
      "scope": "categories",
      "path": "/categories/algorithm/",
      "pageKeys": [
        "v-8bfd3d66",
        "v-6983bd22"
      ]
    },
    "LeetCook": {
      "key": "LeetCook",
      "scope": "categories",
      "path": "/categories/LeetCook/",
      "pageKeys": [
        "v-1f69be38"
      ]
    },
    "blog": {
      "key": "blog",
      "scope": "categories",
      "path": "/categories/blog/",
      "pageKeys": [
        "v-fcfa9c8a"
      ]
    }
  },
  "timeline": {}
}