/**
 * Generated by "@vuepress/plugin-blog"
 */

import sorters from './pageSorters'
import filters from './pageFilters'

export default [{
  pid: "tags",
  id: "heap",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/heap/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "priority-queue",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/priority-queue/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "array",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/array/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "front-end",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/front-end/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "union-find",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/union-find/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "tags",
  id: "graph",
  filter: filters.tags,
  sorter: sorters.tags,
  pages: [{"path":"/tag/graph/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "algorithm",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/algorithm/","interval":[0,2]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "LeetCook",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/LeetCook/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
},
{
  pid: "categories",
  id: "blog",
  filter: filters.categories,
  sorter: sorters.categories,
  pages: [{"path":"/categories/blog/","interval":[0,1]}],
  prevText: "Prev",
  nextText: "Next",
}]